In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../src/all_files.csv")

In [5]:
df

,file_path,file_size,md5,created_time,file_name
0,E:\Backup VLOGS\Episode Backup\1F56A9E0-9DBA-4...,1096337540,24136d2e4f2ad85fe1f849074f26e8bf,1.743862e+09,1F56A9E0-9DBA-425C-AE12-CE603EE247C4.mov
1,E:\Backup VLOGS\Episode Backup\230b8ad1df809e0...,776775471,03c04b9a27058954fc3a390d0b786470,1.743862e+09,230b8ad1df809e087d063ea9dd54b6be_WC-EditVideo_...
2,E:\Backup VLOGS\Episode Backup\copy_1172E9FD-E...,1538686698,170d6cef64537b6689084c8d6ace4011,1.743862e+09,copy_1172E9FD-E9C9-46B5-8BF6-7C283A2EB237.mov
3,E:\Backup VLOGS\Episode Backup\copy_26368007-6...,1016518518,4a4fe37d4d18cf4f96fbf525a76f5ae0,1.743862e+09,copy_26368007-65C7-4C6E-BA39-9A86D360E5E2.mov
4,E:\Backup VLOGS\Episode Backup\copy_27EE13EF-9...,1840122717,7343e7c808ebff928d2cd0f911cec6a9,1.743862e+09,copy_27EE13EF-9E71-4F9A-8C13-9D3FBBBCBCA3.MOV
...,...,...,...,...,...
11649,E:\Backup VLOGS\SA trip\Uyuni\X3\VID_20241126_...,104857600,733ef64ed97ef5f38c7806596cb39c20,1.737317e+09,VID_20241126_063515_10_008.insv
11650,E:\Backup VLOGS\SA trip\Uyuni\X3\VID_20241126_...,548907032,cc6b2c04811422c631a9556cbca10225,1.737317e+09,VID_20241126_063604_00_009.insv
11651,E:\Backup VLOGS\SA trip\Uyuni\X3\VID_20241126_...,545259520,0fbc9cebb47ea33d9206d705a279aeab,1.737317e+09,VID_20241126_063604_10_009.insv
11652,E:\Backup VLOGS\SA trip\Uyuni\X3\VID_20241126_...,254338327,b31b492682f576d64c7bb801e901a70d,1.737317e+09,VID_20241126_063735_00_010.insv
11653,E:\Backup VLOGS\SA trip\Uyuni\X3\VID_20241126_...,251658240,3843f5f01f9ba545e2c61d664646cf0c,1.737317e+09,VID_20241126_063735_10_010.insv

In [6]:
duplicates_df = df[df.duplicated('md5', keep=False)].sort_values('md5')

In [7]:
duplicates_df

,file_path,file_size,md5,created_time,file_name
3344,E:\Backup VLOGS\Kyrgyzstan\Issykul day 7\actio...,11029894,01128c5dab78b5e70c9e2ac9b6bed543,1.746873e+09,DJI_20250423161005_0094_D.LRF 2
3343,E:\Backup VLOGS\Kyrgyzstan\Issykul day 7\actio...,11029894,01128c5dab78b5e70c9e2ac9b6bed543,1.746873e+09,DJI_20250423161005_0094_D.LRF
1792,E:\Backup VLOGS\Kyrgyzstan\day 6\action 5pro\D...,35261162,01345a50a850d5df9af5c3df86692592,1.746872e+09,DJI_20250422085042_0042_D.LRF 2
1791,E:\Backup VLOGS\Kyrgyzstan\day 6\action 5pro\D...,35261162,01345a50a850d5df9af5c3df86692592,1.746872e+09,DJI_20250422085042_0042_D.LRF
10468,E:\Backup VLOGS\SA trip\Sheregesh\X3\VID_20250...,7404491928,0159bfacbaaa57b605a44cc3fa1a2900,1.737502e+09,VID_20250107_233752_00_004.insv
...,...,...,...,...,...
3165,E:\Backup VLOGS\Kyrgyzstan\Issykul day 7\actio...,188024842,ffb7a6356a18978d1fd7714f43a01746,1.746873e+09,DJI_20250423082812_0064_D.MP4
2005,E:\Backup VLOGS\Kyrgyzstan\day 8\action 5 pro\...,61269035,ffc54bf4730c0a74dcbf628569e2b420,1.746873e+09,DJI_20250424145004_0124_D 2.MP4
2009,E:\Backup VLOGS\Kyrgyzstan\day 8\action 5 pro\...,61269035,ffc54bf4730c0a74dcbf628569e2b420,1.746873e+09,DJI_20250424145004_0124_D.MP4
8736,E:\Backup VLOGS\SA trip\Panama\DJI_20241222161...,4259884,ffd30c3cb0d27df4a00be102d2eac028,1.737314e+09,DJI_20241222161835_0009_D 2.WAV
8739,E:\Backup VLOGS\SA trip\Panama\DJI_20241222161...,4259884,ffd30c3cb0d27df4a00be102d2eac028,1.737314e+09,DJI_20241222161835_0009_D.WAV